//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiharITI.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP
    {
        public int id { get; set; }
        public string lat { get; set; }
        public string longitude { get; set; }
        public string deviceid { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string DeviceTime { get; set; }
    }
}
